# Generated by Django 4.2.25 on 2025-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
