# Generated by Django 4.2.25 on 2025-11-10 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
