# Generated by Django 4.2.25 on 2025-11-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unique_id',
            field=models.CharField(max_length=255),
        ),
    ]
