# Generated by Django 4.2.25 on 2025-11-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_usersconnected'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersconnected',
            name='nbr_connected',
            field=models.IntegerField(default=0),
        ),
    ]
