# Generated by Django 4.2.25 on 2025-10-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0002_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
