# Generated by Django 4.2.25 on 2025-10-13 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0003_tip_downvote_tip_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='upvote',
        ),
        migrations.AddField(
            model_name='tip',
            name='downvote',
            field=models.ManyToManyField(related_name='downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
