# Generated by Django 4.2.25 on 2025-10-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0004_remove_tip_downvote_remove_tip_upvote_tip_downvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_permission',
            field=models.BooleanField(default=False),
        ),
    ]
