# Generated by Django 4.2.25 on 2025-10-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0005_myuser_has_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='has_permission',
            new_name='has_permissio',
        ),
    ]
