# Generated by Django 4.2.25 on 2025-10-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0006_rename_has_permission_myuser_has_permissio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='has_permissio',
            new_name='has_permission',
        ),
    ]
