# Generated by Django 4.2.25 on 2025-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0007_rename_has_permissio_myuser_has_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='can_downvote',
            field=models.BooleanField(default=False),
        ),
    ]
