# Generated by Django 4.2.25 on 2025-10-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0008_myuser_can_downvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
