# Generated by Django 5.2.7 on 2025-10-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='caracteres',
            new_name='characters',
        ),
    ]
