# Generated by Django 5.2.7 on 2025-10-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planets',
            old_name='orbiter_period',
            new_name='orbital_period',
        ),
    ]
