# Generated by Django 5.2.7 on 2025-10-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0004_alter_planets_surface_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='orbital_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='rotation_period',
            field=models.IntegerField(null=True),
        ),
    ]
