# Generated by Django 5.2.7 on 2025-10-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0005_alter_planets_orbital_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='terrain',
            field=models.CharField(null=True),
        ),
    ]
