# Generated by Django 5.2.7 on 2025-10-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0006_alter_planets_climate_alter_planets_terrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.IntegerField(null=True),
        ),
    ]
