# Generated by Django 5.2.7 on 2025-10-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0007_alter_planets_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(db_column='homeworld', null=True, on_delete=django.db.models.deletion.CASCADE, to='ex09.planets', to_field='name'),
        ),
    ]
