# Generated by Django 5.2.7 on 2025-10-11 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0009_alter_people_birth_year_alter_people_eye_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
