# Generated by Django 4.2.25 on 2025-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favourites',
            field=models.ManyToManyField(related_name='favourite', to='blog.article'),
        ),
    ]
